name: Build Project for PR

on:
  # Запуск только при создании(обновлении) PR в ветку main
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: клонируем код
      - name: Checkout code
        uses: actions/checkout@v4

      # Шаг 2: Устанавливаем JDK 25
      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: '25'
          distribution: 'temurin'

      # Шаг 3: Компиляция проекта
      - name: Compile with Maven
        run: mvn --batch-mode clean compile

      # Шаг 4: запуск тестов
      - name: Run tests
        run: mvn -B test

      # Шаг 5: запуск проверки стиля кода
      - name: Run Checkstyle for payment-service-app
        working-directory: ./payment-service-app
        run: mvn -B checkstyle:check